-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 17:51:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autobuy
-- -----------------------------------------------------
-- BANCO DE DADOS DA APLICAÇÃO AUTOBUY

-- -----------------------------------------------------
-- Schema autobuy
--
-- BANCO DE DADOS DA APLICAÇÃO AUTOBUY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autobuy` ;
USE `autobuy` ;

-- -----------------------------------------------------
-- Table `autobuy`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autobuy`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `foto` LONGBLOB NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `ano` DATE NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `quilometragem` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idveiculo`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `autobuy`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autobuy`.`anuncio` (
  `idanuncio` INT NOT NULL AUTO_INCREMENT,
  `vendedor` VARCHAR(45) NOT NULL,
  `compradorInteressado` VARCHAR(45) NOT NULL,
  `veiculo` VARCHAR(45) NOT NULL,
  `pagamento` VARCHAR(45) NOT NULL,
  `dataPublicacao` DATE NOT NULL,
  `validacao` TINYINT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `veiculo_idveiculo` INT NOT NULL,
  PRIMARY KEY (`idanuncio`, `veiculo_idveiculo`),
  INDEX `fk_anuncio_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  CONSTRAINT `fk_anuncio_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `autobuy`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autobuy`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autobuy`.`login` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(8) NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autobuy`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autobuy`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` CHAR NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `vendedor` TINYINT NOT NULL,
  `anuncio` VARCHAR(45) NOT NULL,
  `compra` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `veiculocol` VARCHAR(45) NOT NULL,
  `anuncio_idanuncio` INT NOT NULL,
  `login_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`, `anuncio_idanuncio`, `login_login`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_cliente_anuncio_idx` (`anuncio_idanuncio` ASC) VISIBLE,
  INDEX `fk_cliente_login1_idx` (`login_login` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_anuncio`
    FOREIGN KEY (`anuncio_idanuncio`)
    REFERENCES `autobuy`.`anuncio` (`idanuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_login1`
    FOREIGN KEY (`login_login`)
    REFERENCES `autobuy`.`login` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '				';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
